FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Zephyr

Zephyr är ett API vars funktioner ger användaren en musiklista väl anpassat till
det nuvarande vädret. Det är en mobil applikaion där användaren anger på vilken ort
hen befinner sig. Ortsnamnet skickas med som parameter till Google maps API och
returnerar de korrekta kordinaterna som därefter skickas vidare till SMHI´s API. SMHI
returnerar den aktuella temperaturen samt vilket väder det är just nu. Det finns 15
olika väderalternativ, från helt klart till åska. Vädret anger ett specifikt "moode"
till spotify som returnerar en passande spellista. Användaren får på egen hand logga 
in på spotify och Zephyr har inte någon delaktighet i den inloggningen. Alla svar 
från de tre API:n skickas i JSON. Applikationen är byggd i python, HTML och CSS.


## Koordinater [/'https://maps.googleapis.com/maps/api/geocode/json?address='+ city + '&key=' + api_key]
Med namn på vald stad kan rätt koordinater hämntas från SMHI´s API. För att få åtkomst till
SMHI´s API krävs en API_KEY. Denne ska skickas med i förfrågan för att SMHI ska returnera
koordinaterna.

### Hämta vald stads koordinater från SMHI [GET]
+ parameters 
    + city: I följande exempel är den valda parametern Malmö. 
    city är en variabel som innehåller den stad användaren har angivit i
    ett formulär att hen befinner sig i. Variabeln skickas med som parameter till
    till funktionen get_coordinates (`1`)
+ response 200 (application/json)
+ response 404 (html)

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }